### ISSUE TITLE
Why not django-rest-framework?

### ISSUE THREAD

**Issue by dataminion** [pj-simpson/django-ninja-tutorial#1]
How would you compare what you are doing here to the django-rest-framework is there something you are accomplishing here that accomplishes different goals?

**Comment by pj-simpson** [comment]
The repo IS a comparison with django-rest-framework... that was the motivation!

 drf_service/ replicates the same (trivial) app as contained in ninja_service/, each using the different framework. 

I would certainly use Ninja over DRF if I needed to make my code asynchronous (as the latter doesn't support async views yet,[ and perhaps wont for a while longer](https://github.com/encode/django-rest-framework/issues/7260#issuecomment-611399091)). There is some interesting benchmarking [HERE](https://github.com/vitalik/django-ninja-benchmarks)
 
Ninja emphasizes Function Based Views over Class Based, whilst its probably fairly to say that DRF does the opposite (as it has a battle hardened set of Generic Class Based Views). I know these things are ultimately a matter of taste,[ but there seems to be an increasing number of developers who are willing to come out to bat for the simpler FBV style, these days](https://spookylukey.github.io/django-views-the-right-way/index.html)! 

Pydantic schemas is another thing you get for free, so that's data validation with clear and useful error messages, and it basically forces you to use (much more) type checking ([another thing the python community is embracing](https://dropbox.tech/application/our-journey-to-type-checking-4-million-lines-of-python)) 

You also don't have to 'plug in' Swagger as a separate package like you with with DRF, the docs just auto generate. 

-----------------------------------------------------------------------------

Now to actually find some time to use it in a real life project! :)

**Comment by dataminion** [comment]
have you looked at facebook's pyre lib that would be a cool thing to integrate here.

**Comment by pj-simpson** [comment]
Ah no, I'd actually never heard of that. I guess Mypy dominates the static type checking in Python atm... Truth be told im not actually wedded to one particular type checker, as I'm using Pycharm and relying on the typing features there.... I'll give it a go and let you know what I think. Thanks Austin!
